default: &default
  adapter: postgresql
  host: database
  user: postgres
  port: 5432
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lumberjack_dev

test:
  <<: *default
  database: lumberjack_test

production:
  <<: *default
  database: lumberjack_prod
